name: "Terraform Custom Plan"

on:
  pull_request:

env:
  AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
  AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
  

jobs:
  terraform:
    name: "Terraform Custom Plan"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        working-directory: ./tf-actions-test

        run: |
          terraform init
          terraform plan
