name: "Terraform Custom apply"

on:
  push:
    branches:
      - main

env:
  AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
  AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
  

jobs:
  terraform:
    name: "Terraform Custom Plan"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: applying terraform
        working-directory: ./tf-actions-test
        run: terraform apply
