name: TF-validator
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
env:
  TF_CLOUD_ORGANIZATION: "husamag-test"
  TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"
  TF_WORKSPACE: "tf-vpc"
  CONFIG_DIRECTORY: "./"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: format and validate terraform step
        working-directory: ./tf-vpc
        run: |
          terraform init
          terraform fmt
          terraform validate
