name: TF-validator
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    env:
      name: test-env
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: format and validate terraform step
        working-directory: ./tf-vpc
        run: |
          terraform init
          terraform fmt
          terraform validate
